College Recommender Score (#45)
* Delete applications (#10)

* Testing (#11)

* Test some user functions

* Finish first tests for student

* Change college routees

* check if deleting user cascades, adds testing for other attributes of student

* Test admin functions

* more work done on college, application, and testIndex

* unit testing works

* Minor changes to tests

Co-authored-by: swuleung <sammiwuleung@gmail.com>

* College scorecard & testing + Admin UI (#9)

* Base Code

* Remove node_modules and update git ignore

* Sequelize Base with connection to MySQL

* Add in the home page

* Replace Jade with Pug

* Be able to create user

* Completed back-end implementation

* Finished create account form

* Minor css changes

* Restructure directories

* Change view engine to pug

* Login & session (#2)

* Back-end login implementation with JWT

* Fix file path in auth.js

* Add login page & change style of create page

* Fix back-end bcrypt promise

* Add logout ability & navbar change

* modded gitignore to ignore config and c4me keys

* Added the RSA private/public keys

* Auto-add the admin user

* Modify validation of JWT

* Fix login cookies

* Minor fix for correcting function name

* College model (#3)

* Create college model and rank scraping

* Update college model and create major model

* Add scrape collegedata.com export and route

* Add scraping of majors and error catching

* Fix many to many relationship

* Change getadmin to checkadmin

* Add authentication to scrape routes

* Minor changes in values

Co-authored-by: swuleung <sammiwuleung@gmail.com>

* Add primary key for Major to not add dupes

* View & Edit Student Profile (#4)

* View Student Profile

* React bootrap items

* Edit Profile front-end load

* Edit Profile back-end & front-end

* Change the workings of applications + authentication fixes

* Comment on Application

* Add & update applications (front & back)

* Fixed loading and redirecting when trying to edit another user

* On create, go to login page

* Fix edit profile button

* Fix minor errors in profile page & updating

* Change const to let

* Remove loaded & filter existing applications

* toString all values in CollegeDropdown

* Added padding to bottom of app & null fix in CollegeDropdown

* Null issue in applications

* Complete import college scorecard

* Complete front end for scraping/importing

* Add delete students to admin front end

* Minor changes to fix error sending and validation

* Add import student profile to admin page

* Complete admin controls page

* Add testing to import college scorecard

* Minor changes to UI

* Add admin success alert

Co-authored-by: swuleung <sammiwuleung@gmail.com>
Co-authored-by: Zysberg.Zachary.1556769440 <zachary.d.zysberg@nga.mil>

* created searchRouter and added route to app.js

* Refactoring (#12)

* Add eslint & lint app.js

* Ignore console.log & lint bin/www

* Line models folder

* Lint routes folder

* Line tests folder + add some extra rules

* Move colleges.txt to assets

* Move public/private keys to assets

* Line auth.js

* Lint controllers except for adminController

* Lint adminController & restore longform

* Finish linting back-end

* Lint front-end

* minor fix

* making changes in searchController

* Change tests

* Change application to take dynamic college id

* finished a few search filters

* Add high school city & state

* added comments

* added searchRouter to app.js

* Search david (#13)

* added searchController.js

* created searchRouter and added route to app.js

* minor fix

* making changes in searchController

* finished a few search filters

* added comments

* added searchRouter to app.js

Co-authored-by: songdavid98 <songdavid98@gmail.com>

* comment edits

* Early search (#13)

* added searchController.js

* created searchRouter and added route to app.js

* minor fix

* making changes in searchController

* finished a few search filters

* added comments

* added searchRouter to app.js

Co-authored-by: songdavid98 <songdavid98@gmail.com>

* College Profile Page (#15)

* Base Code

* Remove node_modules and update git ignore

* Sequelize Base with connection to MySQL

* Add in the home page

* Replace Jade with Pug

* Be able to create user

* Completed back-end implementation

* Finished create account form

* Minor css changes

* Restructure directories

* Change view engine to pug

* Login & session (#2)

* Back-end login implementation with JWT

* Fix file path in auth.js

* Add login page & change style of create page

* Fix back-end bcrypt promise

* Add logout ability & navbar change

* modded gitignore to ignore config and c4me keys

* Added the RSA private/public keys

* Auto-add the admin user

* Modify validation of JWT

* Fix login cookies

* Minor fix for correcting function name

* College model (#3)

* Create college model and rank scraping

* Update college model and create major model

* Add scrape collegedata.com export and route

* Add scraping of majors and error catching

* Fix many to many relationship

* Change getadmin to checkadmin

* Add authentication to scrape routes

* Minor changes in values

Co-authored-by: swuleung <sammiwuleung@gmail.com>

* Add primary key for Major to not add dupes

* View & Edit Student Profile (#4)

* View Student Profile

* React bootrap items

* Edit Profile front-end load

* Edit Profile back-end & front-end

* Change the workings of applications + authentication fixes

* Comment on Application

* Add & update applications (front & back)

* Fixed loading and redirecting when trying to edit another user

* On create, go to login page

* Fix edit profile button

* Fix minor errors in profile page & updating

* Change const to let

* Remove loaded & filter existing applications

* toString all values in CollegeDropdown

* Added padding to bottom of app & null fix in CollegeDropdown

* Null issue in applications

* Complete import college scorecard

* Complete front end for scraping/importing

* Add delete students to admin front end

* Minor changes to fix error sending and validation

* Add import student profile to admin page

* Complete admin controls page

* College profile start

* Delete duplicate functions in adminController

* Higher Level Overview Done

* Finish College Profile Page

* Setup concurrent start of front-end and back-end

* Minor changes in UI

Co-authored-by: Jackie Quach <jackiequach14@gmail.com>
Co-authored-by: Zysberg.Zachary.1556769440 <zachary.d.zysberg@nga.mil>
Co-authored-by: Jackie Quach <37321861+jackiequach@users.noreply.github.com>

* High school model and controller created (#17)

Co-authored-by: Jackie Quach <jackiequach14@gmail.com>

* Applications tracker back-end (#16)

Needs to be verified

* location and cost filter completed. 1 major complete. to do 2 majors

* 2 majors can be filtered for now

* Applications tracker scatterplot (#19)

* Filter applications & build query

* Applications Tracker Summary

* No filters = all of them for statuses

* Add average GPA & rounding to applications tracker

* Add high school route

* Temporarily finish applications tracker scatterplot

* Change labels & min/max

* from star to triangle for 'you

* Average weight calculation fix

* Change  high school  display

* Change default back to overview tab

* Scrape highschool (#18)

* High school model and controller created

* Add routing for high schools

* Complete scraping for high school data

Co-authored-by: swuleung <sammiwuleung@gmail.com>

* Scrape highschool GET to POST (#20)

* High school model and controller created

* Add routing for high schools

* Complete scraping for high school data

* Change route from GET to POST

Co-authored-by: Jackie Quach <jackiequach14@gmail.com>

* Logout and moving services (#21)

* Move create-account service

* Move login to service/api

* Fix loging/logout cookies and remove js-cookie

* Comma dangle for college.js

* Verify admin

* Line ATScattereplot

* Fix react issues with useEffect

* Fix more react & linting errors in App.js & FilterAT.js

* Fix college error

* Display List for Applications Tracker (#22)

* Display List

* Fix go to profile link

* comments

* complied with requests. changed route and code

* created search.js in api

* Import student with highschools from table (#23)

* Scrape highschool integration to edit/view profile (#25)

* High school model and controller created

* Add routing for high schools

* Complete scraping for high school data

* Change route from GET to POST

* Started implementing scrape to edit profile

* Fix too many set states

* Attempt to get data for high school from backend

* Completed integration of scraping high school to edit profile

* Complete integration of high school to student profile

* Fix minor front end error

* Fix PR requests

* Move other to beginning of high school list

* Update capitalization for high school names

Co-authored-by: swuleung <sammiwuleung@gmail.com>

* Update import student and linted back-end (#27)

* High school model and controller created

* Add routing for high schools

* Complete scraping for high school data

* Change route from GET to POST

* Started implementing scrape to edit profile

* Fix too many set states

* Attempt to get data for high school from backend

* Completed integration of scraping high school to edit profile

* Complete integration of high school to student profile

* Fix minor front end error

* Fix PR requests

* Move other to beginning of high school list

* Update capitalization for high school names

* Lint backend

* Change import student to use update high school

Co-authored-by: swuleung <sammiwuleung@gmail.com>

* basic skeleton for search component

* added search in components

* pulled from master

* Undid work to make sure it still compiles

* 404 on getting applications, might not be calling it correctly

* Included the route...

* Only getting pending promise, no result of query

* Deploy project setup and fix build issues (#29)

* Change to default export for service apis

* Minor text change

* Change proxy to allow fetch with endpoints

* Setup for deploying to Google Cloud

* Test data for students & applications (#24)

* Add test files that are within range of announced size

* Revert high school id change

* Add and move test data

* Change configs

* Change paths to use utils

* Fixed previous tests

* Add applications tracker tests and fix minor bugs

* Lint collegeController

* Fix 0 division

* Minor changes to UI to conform to data

* Postman shows that get request fails, reason is empty(!?)

* Refactoring for Code 2 (#30)

* User comments

* Logout comment in userRouter

* Comment on student

* College comments

* Add some comments to high school and admin

* Add more comments

* Tests and auth comments

* Change cookie date expire

* Comment on front-end components (some)

* Add comments for API

* Add comments

* Add space to package.json

* FIx

Co-authored-by: Jackie Quach <jackiequach14@gmail.com>

* postman gives me a failed get request but clicking button ggives me 200(!?!)

* started resultList

* Fixes after refactoring (#31)

* User comments

* Logout comment in userRouter

* Comment on student

* College comments

* Add some comments to high school and admin

* Add more comments

* Tests and auth comments

* Change cookie date expire

* Comment on front-end components (some)

* Add comments for API

* Add comments

* Add space to package.json

* FIx

* Fix for applications tracker

* Display ApplicationsTracker with college class and school

* Capitalize School

* Fiix high school

* Add space & fix hs filtering again

* Fix SAT typo

Co-authored-by: Jackie Quach <jackiequach14@gmail.com>

* lax filter and backend sorting done and tested

* Connection to mysql with SSL (#33)

* added cert

* Similar highschools page (#34)

* Add grad rate to college model and start find similar hs page

* Finish base find similar high school page

* Add info message for missing hs

Co-authored-by: swuleung <sammiwuleung@gmail.com>

* got rid of search in app

* fixed ca cert

* fixed merge conflicts in app

* Search Colleges (#14)

* added searchController.js

* created searchRouter and added route to app.js

* minor fix

* making changes in searchController

* finished a few search filters

* added comments

* added searchRouter to app.js

* Search david (#13)

* added searchController.js

* created searchRouter and added route to app.js

* minor fix

* making changes in searchController

* finished a few search filters

* added comments

* added searchRouter to app.js

Co-authored-by: songdavid98 <songdavid98@gmail.com>

* comment edits

* location and cost filter completed. 1 major complete. to do 2 majors

* 2 majors can be filtered for now

* comments

* complied with requests. changed route and code

* created search.js in api

* basic skeleton for search component

* added search in components

* pulled from master

* started resultList

* lax filter and backend sorting done and tested

* added cert

* got rid of search in app

* fixed ca cert

* fixed merge conflicts in app

Co-authored-by: songdavid98 <songdavid98@gmail.com>

* gave rankingmin and max lax filtering ability

* Deploy project changes & fixes for high school (#32)

* Change to default export for service apis

* Minor text change

* Change proxy to allow fetch with endpoints

* Setup for deploying to Google Cloud

* Create script to simplify deployment

* Put space in package.json

* Change files for deployment

* Fix naming issues

* fix filter query

* Change high school in edit profile

* Fix college data page closing

* Add chromium into package.json

* Wrap error catching

* modify college class

* Update college class

* Switch around caluses for between collegeclass

* Fixed college class

* Alphabetize High Schools

* Capitalize High Schools before creating and move other top of every list

* Fix tests and connection

* Add scrape route

* Merge branch

* Fix some scraping issues

* Lint hs

* Update proxies

* Fix high school data

* Remove extra localhost

* Add scroll for high school autosuggest

Co-authored-by: Jackie Quach <jackiequach14@gmail.com>

* try to get apps

* disable buttons while scraping/importing (#28)

* disable buttons while scraping/importing

* Only disable student profiles while either or are clicked

Co-authored-by: Jackie Quach <jackiequach14@gmail.com>

* search router auth

* resolving merge conflicts so it compiles

* Unexpected character at line 1 col 1 for JSON data

* wrote some pseudocode notes for later

* Finished core work, need to update Applications for questionable, call getQuestionableApplications from the front-end, then start debugging

* costMax filter for out of state/in state now functional

* bug fix with student when dealing with costMax

* filtering 2 majors working now as AND instead of OR

* merged with master, overwrote local history, rewriting

* forgot and resolved another merge conflict

* Error: applications.toJSON(); is not a function | in searchController

* applications is already a JSON smfh

* calcQuestionableApps hangs on finding the student based on Application's username

* 'How's it Hanging?'

* TODO: call calcQuestionableApplication for one application when application status becomes denied/accepted

* begin calculating questionable during edit applications

* checking application in student controller instead, before updating applications table, check if new status is accepted/denied, then call qApp to update questionable, THEN update application table

* college recommeder alg almost done. have to do similar students alg

* Revert "TODO: call calcQuestionableApplication for one application when application status becomes denied/accepted"

This reverts commit ef470e48de13cd40b8735ca3fbe1ce02189edaf1.

* created route for college rec

* questionable-acceptance-decision is calculated in the backend

* Didn't check for already existing applications, fixed that

* Trying to make a basic front-end for qApps

* When updating the front end to view the questionable apps, error from react: too many re-renders

* When updating the front end to view the questionable apps, error from react: too many re-renders

* Added front end for questionable applications

* Improved front-end, started back-end

* Made some notes in AdminQApp, ...api\admin.js, adminController, adminRouter

* getting ready to pull db changes

* Update questionable acceptance deecision

* Only send necessary attributes

* Update applications and comments

* Edit questionable acceptance decision algorithm

* Add calculat questionable acceptance decision to import applications

* Remove extra functions

* Update error message

* Leave page after editing

* disabled view of questionable apps when not admin

* Add spinner plus fix warnings

* Add tests for questionable acceptance decision

* Reduce applications tracker function

* Display whether an application is questionable or not

* Add comments

* score comes out now

* Change direction of overlay

* Change wording of popover for questionable decisions

* took into account null values

* turned score into a fraction over maxScore

* fixed typo

* Hide search & find similar hs from navbar if logged out

* Fixed showing search colleges in navbar

* Only update on change of application

* Fix tests to only check when status is changed

* saving changes for similar hs students

* similar hs in search controller

* sim student major score

* finished college recommder alg

* finished up college rec algoruthm

* Update UI to include college recommender

* Make import applications faster with less awaits

* Only calculate if it is questionable on found college

* got rid of >=

* Change weight of tests

* Add professor's sample student data

* Add tests for college recommender

* Change routes to have uniform case

Co-authored-by: Zachary <30755679+Zysberg@users.noreply.github.com>
Co-authored-by: Jackie Quach <37321861+jackiequach@users.noreply.github.com>
Co-authored-by: Zysberg.Zachary.1556769440 <zachary.d.zysberg@nga.mil>
Co-authored-by: songdavid98 <songdavid98@gmail.com>
Co-authored-by: Jackie Quach <jackiequach14@gmail.com>
Co-authored-by: Zachary <zacharyzysberg1@gmail.com>
Co-authored-by: David Song <songdavid98@users.noreply.github.com>